### ISSUE TITLE
ASSERT failure in QCoreApplication::sendEvent

### ISSUE THREAD

**Issue by jaredtao** [edelhirsch/widgetitem#1]
OS： windows 10 1909
Qt：5.12.5
Compiler: msvc 2017_64bit
commit SHA-1: 1c35556744a272c729984dcc5edd46c3489fca14
log:
```
QML debugging is enabled. Only use this in a safe environment.
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0x258bd91b810. Receiver '' (of type 'QPushButton') was created in thread 0x0x258ba412400", file kernel\qcoreapplication.cpp, line 578
```

----------------------------------split line------------------------------------
in my opinion，QWidget use cpu raster and must be use in main thread，but Qml /SceneGraph work in SceneGraph thread.  That's the problem

**Comment by peter-ha** [comment]
Interesting; I only tried this on Linux, and I thought on my setup there was a dedicated scene graph thread as well.
You could try adding an invokable method and call that via a QueuedConnection and then deliver the event from there, maybe it helps...

**Comment by bansan85** [comment]
I have the same problem. I looked on lots of doc on Internet but your implementation looks good.

I finally found that MuseScore use the same pattern. I noticed that the uml render is done on the main thread. I currently investigate to found how they do it.

For the current time, I found that add `qputenv("QT_QUICK_BACKEND", "software");` fix the problem but it's not a good solution.
